# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/projects/lineFollowingDir/dual_lineFollow

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/projects/lineFollowingDir/dual_lineFollow

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/projects/lineFollowingDir/dual_lineFollow/CMakeFiles /home/pi/projects/lineFollowingDir/dual_lineFollow/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/projects/lineFollowingDir/dual_lineFollow/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dualRoboNet

# Build rule for target.
dualRoboNet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dualRoboNet
.PHONY : dualRoboNet

# fast build rule for target.
dualRoboNet/fast:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/build
.PHONY : dualRoboNet/fast

#=============================================================================
# Target rules for targets named clBP

# Build rule for target.
clBP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clBP
.PHONY : clBP

# fast build rule for target.
clBP/fast:
	$(MAKE) -f clBP/CMakeFiles/clBP.dir/build.make clBP/CMakeFiles/clBP.dir/build
.PHONY : clBP/fast

LowPassFilter.o: LowPassFilter.cpp.o

.PHONY : LowPassFilter.o

# target to build an object file
LowPassFilter.cpp.o:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/LowPassFilter.cpp.o
.PHONY : LowPassFilter.cpp.o

LowPassFilter.i: LowPassFilter.cpp.i

.PHONY : LowPassFilter.i

# target to preprocess a source file
LowPassFilter.cpp.i:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/LowPassFilter.cpp.i
.PHONY : LowPassFilter.cpp.i

LowPassFilter.s: LowPassFilter.cpp.s

.PHONY : LowPassFilter.s

# target to generate assembly for a file
LowPassFilter.cpp.s:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/LowPassFilter.cpp.s
.PHONY : LowPassFilter.cpp.s

bandpass.o: bandpass.cpp.o

.PHONY : bandpass.o

# target to build an object file
bandpass.cpp.o:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/bandpass.cpp.o
.PHONY : bandpass.cpp.o

bandpass.i: bandpass.cpp.i

.PHONY : bandpass.i

# target to preprocess a source file
bandpass.cpp.i:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/bandpass.cpp.i
.PHONY : bandpass.cpp.i

bandpass.s: bandpass.cpp.s

.PHONY : bandpass.s

# target to generate assembly for a file
bandpass.cpp.s:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/bandpass.cpp.s
.PHONY : bandpass.cpp.s

external.o: external.cpp.o

.PHONY : external.o

# target to build an object file
external.cpp.o:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/external.cpp.o
.PHONY : external.cpp.o

external.i: external.cpp.i

.PHONY : external.i

# target to preprocess a source file
external.cpp.i:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/external.cpp.i
.PHONY : external.cpp.i

external.s: external.cpp.s

.PHONY : external.s

# target to generate assembly for a file
external.cpp.s:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/external.cpp.s
.PHONY : external.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/main.cpp.s
.PHONY : main.cpp.s

neural.o: neural.cpp.o

.PHONY : neural.o

# target to build an object file
neural.cpp.o:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/neural.cpp.o
.PHONY : neural.cpp.o

neural.i: neural.cpp.i

.PHONY : neural.i

# target to preprocess a source file
neural.cpp.i:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/neural.cpp.i
.PHONY : neural.cpp.i

neural.s: neural.cpp.s

.PHONY : neural.s

# target to generate assembly for a file
neural.cpp.s:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/neural.cpp.s
.PHONY : neural.cpp.s

serialib.o: serialib.cpp.o

.PHONY : serialib.o

# target to build an object file
serialib.cpp.o:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/serialib.cpp.o
.PHONY : serialib.cpp.o

serialib.i: serialib.cpp.i

.PHONY : serialib.i

# target to preprocess a source file
serialib.cpp.i:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/serialib.cpp.i
.PHONY : serialib.cpp.i

serialib.s: serialib.cpp.s

.PHONY : serialib.s

# target to generate assembly for a file
serialib.cpp.s:
	$(MAKE) -f CMakeFiles/dualRoboNet.dir/build.make CMakeFiles/dualRoboNet.dir/serialib.cpp.s
.PHONY : serialib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... dualRoboNet"
	@echo "... edit_cache"
	@echo "... clBP"
	@echo "... LowPassFilter.o"
	@echo "... LowPassFilter.i"
	@echo "... LowPassFilter.s"
	@echo "... bandpass.o"
	@echo "... bandpass.i"
	@echo "... bandpass.s"
	@echo "... external.o"
	@echo "... external.i"
	@echo "... external.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... neural.o"
	@echo "... neural.i"
	@echo "... neural.s"
	@echo "... serialib.o"
	@echo "... serialib.i"
	@echo "... serialib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

